name: Push to Replicate

on:
  push:
    branches:
      - "main"

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    
    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Clear CUDA cache
        run: rm -rf /opt/hostedtoolcache/cuda_installer-linux || true

      - name: Set up CUDA
        uses: Jimver/cuda-toolkit@v0.2.27
        with:
          cuda: "12.2.0"

      - name: Set up Cog
        uses: replicate/setup-cog@v1
        with:
          token: ${{ secrets.REPLICATE_API_TOKEN }}

      - name: Build and push the model
        run: cog push