name: Push to Replicate

on:
  push:
    branches:
      - main

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the repository
      - name: Checkout the repository
        uses: actions/checkout@v3

      # Step 2: Set up Cog
      - name: Set up Cog
        uses: actions/setup-cog@v3
        with:
          token: ${{ secrets.REPLICATE_API_TOKEN }}

      # Step 3: Build and push the model
      - name: Build the model
        uses: cog push
